import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapJSLoad from "./Loaders/BootstrapJSLoad";
import "./globals.css";

export const metadata = {
  title: "Rifat's Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <BootstrapJSLoad />
      </body>
    </html>
  );
}
